<?php

/**
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 *
 * @VERSION Barpay 0.1.2
 *
**/

?>
<a onclick="javascript:window.open('<?php echo $this->__('http://www.barpay.de/info/') ?>','kundeninformationen','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=580, height=550');return false;" href="#" title="Hier klicken - Informationen zu Barpay"><img src="<?php echo $this->getSkinUrl('images/barpay/barpay_checkout.gif') ?>" alt="Hier klicken - Barpay Kundeninformationen" border="0" /></a>
